import path from 'path';
import { BaseAdapter } from './base.js';
import type { SkillDefinition, GeneratedFile } from '../schema/types.js';

export class CursorAdapter extends BaseAdapter {
  readonly id = 'cursor';
  readonly name = 'Cursor';
  readonly skillsDir = '.cursor/skills';
  readonly detectionPaths = ['.cursor/', '.cursorrules'];

  generateSkill(skill: SkillDefinition, targetRoot: string): GeneratedFile[] {
    const skillPath = path.join(this.skillsDir, skill.name, 'SKILL.md');
    const content = this.addGeneratedByMarker(skill.content);
    return [this.createGeneratedFile(skillPath, content)];
  }

  generateCommands(skill: SkillDefinition, targetRoot: string): GeneratedFile[] {
    const rulePath = path.join('.cursor/rules', `${skill.name}.mdc`);
    const ruleContent = this.buildRuleContent(skill);
    return [this.createGeneratedFile(rulePath, ruleContent)];
  }

  generateConfig(skills: SkillDefinition[], targetRoot: string): GeneratedFile[] {
    const snippets = skills.map((s) => `@.cursor/skills/${s.name}/SKILL.md`).join('\n');
    const content = this.buildAgentsMdSnippet(snippets);
    return [this.createGeneratedFile('AGENTS.md.sot-snippet', content)];
  }

  private buildRuleContent(skill: SkillDefinition): string {
    const hint = skill.frontmatter.model_hint || skill.metadata?.model_hint;
    const metadata = [`---`, `description: ${skill.description}`];
    if (hint) metadata.push(`modelHint: ${hint}`);
    metadata.push(`globs:`, `alwaysApply: false`, `---`);
    return this.addGeneratedByMarker(metadata.join('\n') + '\n\n' + skill.content + '\n');
  }

  private buildAgentsMdSnippet(skillRefs: string): string {
    return this.addGeneratedByMarker(`\n<!-- SOT:START - Generated by sot -->\n<!-- SOT:END -->\n\n## Skills\n\nReferences:\n${skillRefs}\n`);
  }
}
